#!/bin/sh

# Check httpd launcher
if [ ! -e /etc/init.d/httpd ]
then
	# Copy over and register init script we already prepared
	cp /home/user/server/scripts/httpd /etc/init.d/
fi

# Check log directories
if [ ! -e /var/log/apache2 ]
then
	mkdir /var/log/apache2
	chown -R root:root /var/log/apache2
fi

if [ -e /tmp/deploy-apache ]
then
	# Lets stop everything first
	/etc/init.d/httpd stop
	
	# Copy configuration back
	cp /home/user/server/config/httpd.conf $ROOT_PREFIX/conf/
	
	# Do a swap-around
	mv  $ROOT_PREFIX /usr/old-apache
	mv /tmp/deploy-apache $ROOT_PREFIX
	rm -rf /usr/old-apache
	
	# Setup the permissions
	chown -R root:root  $ROOT_PREFIX
	chmod 755 $ROOT_PREFIX
	chmod 755 $ROOT_PREFIX/bin
	chmod 755 $ROOT_PREFIX/conf
	chmod 755 $ROOT_PREFIX/logs # preferrably a-r
	# Assuming httpd is root:root
	chmod 511 $ROOT_PREFIX/bin/httpd
	
	# Start everything back up again
	/etc/init.d/httpd start
else
	echo "No deployment directory present. Cannot deploy!"
	exit 1
fi
	